CBV_todo/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Todo Api",
        default_version="v1",
        description="That's all the Api on the website.",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="biroghlan95@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo.urls")),
    path("accounts/", include("accounts.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api-docs/", include_docs_urls(title="api-docs")),
    path(
        "swagger/todo-api.json/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

accounts/api/v1/urls.py
from django.urls import path
from rest_framework.authtoken import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

urlpatterns = [
    # token git authenticated
    path('auth-token/', views.obtain_auth_token),

    # jwt authenticated
    path('jwt/create/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('jwt/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('jwt/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('send_email/', views.send_email, name='send_email'),
    path('login/', views.LoginView.as_view(), name="login"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('api/v1/', include('accounts.api.v1.urls')),
]

todo/api/v1/urls.py
from rest_framework import routers
from . import views

app_name = "api-v1"


router = routers.DefaultRouter()

router.register("task", views.TaskViewSet, basename="task")
urlpatterns = router.urls

todo/urls.py
from django.urls import path, include
from . import views


app_name = "todo"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path('weather', views.weather, name="weather"),
    path("create/", views.TaskCreateView.as_view(), name="create"),
    path("update/<int:pk>/", views.TaskUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.TaskDeleteView.as_view(), name="delete"),
    path("done/<int:pk>/", views.TaskDoneView.as_view(), name="done"),
    path("undone/<int:pk>/", views.TaskUndoneView.as_view(), name="undone"),
    path("api/v1/", include("todo.api.v1.urls")),
]

accounts/models.py
# from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Task(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    done = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name"]

todo/forms.py
from django import forms


class TaskForm(forms.Form):
    title = forms.CharField()

accounts/views.py
# from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from .tasks import sendemail


# Create your views here.


class LoginView(LoginView):
    template_name = "accounts/login.html"
    fields = "username", "password"


class SignUpView(CreateView):
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("todo:index")
    form_class = UserCreationForm

def send_email(request):
    sendemail.delay()
    return HttpResponse('<h1>Your email sent!</h1>')

todo/api/v1/views.py
from .serializers import TaskSerializer
from rest_framework import filters
from rest_framework import permissions
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from todo.models import Task


class TaskViewSet(viewsets.ModelViewSet):
    permission_classes = [permissions.IsAuthenticated]
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    filter_backends = (
        DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )
    search_fields = ("title",)
    ordering_fields = ["created_date", "done"]

    def get_queryset(self):
        """
        Getting user for not having access to the rest of the Task.
        """
        if self.request.user.is_superuser:
            return Task.objects.all()
        return Task.objects.filter(owner=self.request.user)

todo/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.views import View
from django.views.decorators.cache import cache_page
from django.http import JsonResponse
import requests, json
from .models import Task

# Create your views here.


class IndexView(LoginRequiredMixin, ListView):
    model = Task

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["title"]
    success_url = reverse_lazy("todo:index")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(TaskCreateView, self).form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ("title",)
    success_url = reverse_lazy("todo:index")

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy("todo:index")

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)


class TaskDoneView(LoginRequiredMixin, View):
    model = Task
    success_url = reverse_lazy("todo:index")

    def get(self, request, *args, **kwargs):
        object = Task.objects.get(id=kwargs.get("pk"))
        object.done = True
        object.save()
        return redirect(self.success_url)


class TaskUndoneView(LoginRequiredMixin, View):
    model = Task
    success_url = reverse_lazy("todo:index")

    def get(self, request, *args, **kwargs):
        object = Task.objects.get(id=kwargs.get("pk"))
        object.done = False
        object.save()
        return redirect(self.success_url)

@cache_page(60 * 20)
def weather(request):
    """
        It shows the weather condition of Tabriz city and updates every 20 minutes.
    """
    base_url = "http://api.openweathermap.org/data/2.5/weather?"
    api_key = "80c8173748c3690246d4c2488e06feb7"
    city = "Tabriz"
    url = base_url + "appid=" + api_key + "&q=" + city
    response = requests.get(url)
    return JsonResponse(response.json())

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login"> 
    </form>
    <h4>Do you have account?! <a href="{% url 'accounts:signup' %}">Signup</a></h4>
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="signup"> 
    </form>
</body>
</html>

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

todo/templates/todo/task_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

todo/templates/todo/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create message">
    </form>
</body>
</html>

todo/templates/todo/task_list.html
{% extends "base.html" %}
{% block content %}

<h2>Publishers</h2>
<ul>
    <div>
        <a href="{% url 'todo:create' %}">
            <h3>
                Create Todo
            </h3></a>
    </div>
    <hr>
    <span>
    {% for task in object_list %}
    {% if task.done == True %}
    <li><strike>{{task.title}}</strike><br></li>
    <a href="{% url 'todo:delete'  pk=task.pk %} ">Delete</a> /
    <a href="{% url 'todo:undone'  pk=task.pk %} ">Undone</a><br>
    {% else %}
    <li> {{ task.title }}</li><br>
    <div>
        <a href="{% url 'todo:update'  pk=task.pk %} ">Update</a> /
        <a href="{% url 'todo:delete'  pk=task.pk %} ">Delete</a> /
        <a href="{% url 'todo:done'  pk=task.pk %} ">Done</a>
        
    </div>
    </span><br>
    {% endif %}
    {% endfor %}
    </ul>
{% endblock %}